Repository Graylog2/graylog-plugin-integrations, pull requests merged in 2019-06, with the labels that each got.

#52 Update yarn.lock
  yarn.lock
Labels: ready-for-review

#54 Kinesis-related code cleanup
  src/main/java/org/graylog/integrations/aws/KinesisService.java
  src/main/java/org/graylog/integrations/aws/resources/responses/KinesisHealthCheckResponse.java
  src/main/java/org/graylog/integrations/aws/resources/responses/RegionResponse.java
Labels: ready-for-review

#75 General UI Skeleton
  .eslintrc.json
  package.json
  src/web/aws-cloudwatch/CloudWatch.jsx
  src/web/aws-cloudwatch/FormAdvancedOptions.jsx
  src/web/aws-cloudwatch/KinesisSetup.jsx
  src/web/aws-cloudwatch/KinesisStreams.jsx
  src/web/aws-cloudwatch/StepAuthorize.jsx
  src/web/aws-cloudwatch/StepHealthCheck.jsx
  src/web/aws-cloudwatch/StepKinesis.jsx
  src/web/aws-cloudwatch/StepReview.jsx
  src/web/aws/Services.jsx
  src/web/index.jsx
  yarn.lock
Labels: aws, improvement, ux

#76 Add retrievelogs for Kinesis Healthcheck
  pom.xml
  src/main/java/org/graylog/integrations/aws/KinesisService.java
  src/main/java/org/graylog/integrations/aws/Main.java
  src/main/java/org/graylog/integrations/aws/service/AWSService.java
  src/test/java/org.graylog.integrations/aws/KinesisServiceTest.java
Labels: M1 - backend setup, aws, backend, ready-for-review

#86 Aws health check
  src/main/java/org/graylog/integrations/aws/KinesisService.java
  src/main/java/org/graylog/integrations/aws/Main.java
  src/main/java/org/graylog/integrations/aws/cloudwatch/CloudWatchLogEvent.java
  src/test/java/org.graylog.integrations/aws/KinesisServiceTest.java
Labels: ready-for-review

#90 Backend Code Cleanup
  src/main/java/org/graylog/integrations/aws/AWSLogMessage.java
  src/main/java/org/graylog/integrations/aws/resources/AWSResource.java
  src/main/java/org/graylog/integrations/aws/service/AWSService.java
  src/main/java/org/graylog/integrations/aws/service/CloudWatchService.java
  src/main/java/org/graylog/integrations/aws/service/KinesisService.java
  src/test/java/org.graylog.integrations/aws/cloudwatch/CloudWatchServiceTest.java
  src/test/java/org.graylog.integrations/aws/resources/AWSResourceTest.java
  src/test/java/org.graylog.integrations/aws/service/AWSServiceTest.java
  src/test/java/org.graylog.integrations/aws/service/KinesisServiceTest.java
Labels: ready-for-review

#110 Update region api call
  src/main/java/org/graylog/integrations/aws/resources/AWSResource.java
  src/main/java/org/graylog/integrations/aws/resources/responses/AWSRegion.java
  src/main/java/org/graylog/integrations/aws/resources/responses/RegionsResponse.java
  src/main/java/org/graylog/integrations/aws/service/AWSService.java
  src/test/java/org.graylog.integrations/aws/service/AWSServiceTest.java
Labels: ready-for-review

#92 Pass region and AWS credentials with AWS API requests
  src/main/java/org/graylog/integrations/aws/resources/AWSResource.java
  src/main/java/org/graylog/integrations/aws/resources/requests/AWSRequestImpl.java
  src/main/java/org/graylog/integrations/aws/resources/responses/AWSRegion.java
  src/main/java/org/graylog/integrations/aws/resources/responses/AvailableService.java
  src/main/java/org/graylog/integrations/aws/resources/responses/AvailableServiceResponse.java
  src/main/java/org/graylog/integrations/aws/resources/responses/HealthCheckResponse.java
  src/main/java/org/graylog/integrations/aws/resources/responses/LogGroupsResponse.java
  src/main/java/org/graylog/integrations/aws/resources/responses/RegionResponse.java
  src/main/java/org/graylog/integrations/aws/resources/responses/RegionsResponse.java
  src/main/java/org/graylog/integrations/aws/resources/responses/StreamsResponse.java
  src/main/java/org/graylog/integrations/aws/service/AWSService.java
  src/main/java/org/graylog/integrations/aws/service/CloudWatchService.java
  src/main/java/org/graylog/integrations/aws/service/KinesisService.java
  src/test/java/org.graylog.integrations/aws/cloudwatch/CloudWatchServiceTest.java
  src/test/java/org.graylog.integrations/aws/service/AWSServiceTest.java
  src/test/java/org.graylog.integrations/aws/service/KinesisServiceTest.java
Labels: ready-for-review

#113 Aws permissions check
  src/main/java/org/graylog/integrations/IntegrationsModule.java
  src/main/java/org/graylog/integrations/aws/AWSPermissions.java
  src/main/java/org/graylog/integrations/aws/resources/AWSResource.java
Labels: ready-for-review

#93 Save AWS input API endpoint
  src/main/java/org/graylog/integrations/IntegrationsModule.java
  src/main/java/org/graylog/integrations/aws/AWSLogMessage.java
  src/main/java/org/graylog/integrations/aws/AWSMessageType.java
  src/main/java/org/graylog/integrations/aws/AWSPermissions.java
  src/main/java/org/graylog/integrations/aws/AWSUtils.java
  src/main/java/org/graylog/integrations/aws/cloudwatch/CloudWatchLogEntry.java
  src/main/java/org/graylog/integrations/aws/cloudwatch/FlowLogMessage.java
  src/main/java/org/graylog/integrations/aws/cloudwatch/KinesisLogEntry.java
  src/main/java/org/graylog/integrations/aws/codecs/AWSMetaCodec.java
  src/main/java/org/graylog/integrations/aws/codecs/AbstractKinesisCodec.java
  src/main/java/org/graylog/integrations/aws/codecs/KinesisCloudWatchFlowLogCodec.java
  src/main/java/org/graylog/integrations/aws/codecs/KinesisRawLogCodec.java
  src/main/java/org/graylog/integrations/aws/inputs/AWSInput.java
  src/main/java/org/graylog/integrations/aws/resources/AWSResource.java
  src/main/java/org/graylog/integrations/aws/resources/requests/AWSInputCreateRequest.java
  src/main/java/org/graylog/integrations/aws/resources/requests/KinesisHealthCheckRequest.java
  src/main/java/org/graylog/integrations/aws/resources/responses/HealthCheckResponse.java
  src/main/java/org/graylog/integrations/aws/service/AWSService.java
  src/main/java/org/graylog/integrations/aws/service/KinesisService.java
  src/main/java/org/graylog/integrations/aws/transports/KinesisTransport.java
  src/test/java/org.graylog.integrations/aws/cloudwatch/FlowLogMessageTest.java
  src/test/java/org.graylog.integrations/aws/codecs/CloudWatchFlowLogCodecTest.java
  src/test/java/org.graylog.integrations/aws/resources/AWSResourceTest.java
  src/test/java/org.graylog.integrations/aws/service/AWSServiceTest.java
  src/test/java/org.graylog.integrations/aws/service/KinesisServiceTest.java
Labels: ready-for-review
