Repository Graylog2/graylog-plugin-integrations, pull requests merged in 2020-10, with the labels that each got.

#581 Reusing link component abstraction from core.
  src/web/aws/StepAuthorize.jsx
  src/web/aws/authentication/AWSAuthenticationTypes.jsx
  src/web/aws/authentication/AWSCustomEndpoints.jsx
  src/web/aws/cloudwatch/CloudWatch.jsx
  src/web/aws/cloudwatch/CloudWatchApp.jsx
  src/web/aws/cloudwatch/FormAdvancedOptions.jsx
  src/web/aws/cloudwatch/SidebarPermissions.jsx
  src/web/aws/cloudwatch/StepHealthCheck.jsx
  src/web/aws/cloudwatch/StepKinesis.jsx
  src/web/aws/cloudwatch/StepReview.jsx
  src/web/aws/cloudwatch/kinesis/ExistingStreams.jsx
  src/web/aws/cloudwatch/kinesis/SetupNewStream.jsx
  src/web/aws/cloudwatch/kinesis/setup-steps/KinesisSetupSteps.jsx
  src/web/aws/cloudwatch/kinesis/setup-steps/SetupModal.jsx
  src/web/aws/common/AdditionalFields.jsx
  src/web/aws/common/FormWrap.jsx
  src/web/aws/common/Options.jsx
  src/web/aws/common/Routes.js
  src/web/aws/common/SkipHealthCheck.jsx
  src/web/aws/common/ValidatedInput.jsx
  src/web/aws/context/AdvancedOptions.jsx
  src/web/aws/context/Api.jsx
  src/web/aws/context/FormData.jsx
  src/web/aws/context/Steps.jsx
  src/web/aws/utils/formValidation.js
Labels: ready-for-review

#582 Reuse `withParams` abstraction from core.
  src/web/aws/cloudwatch/CloudWatchApp.jsx
Labels: ready-for-review

#599 Remove `--bail` flag from webpack build.
  package.json
Labels: ready-for-review

#595 Slack plugin v001
  .eslintrc.json.bak
  package.json
  pom.xml
  src/main/java/org/graylog/integrations/IntegrationsModule.java
  src/main/java/org/graylog/integrations/notifications/types/SlackClient.java
  src/main/java/org/graylog/integrations/notifications/types/SlackEventNotification.java
  src/main/java/org/graylog/integrations/notifications/types/SlackEventNotificationConfig.java
  src/main/java/org/graylog/integrations/notifications/types/SlackEventNotificationConfigEntity.java
  src/main/java/org/graylog/integrations/notifications/types/SlackMessage.java
  src/test/java/org/graylog/integrations/notifications/types/SlackClientTest.java
  src/test/java/org/graylog/integrations/notifications/types/SlackEventNotificationConfigTest.java
  src/test/java/org/graylog/integrations/notifications/types/SlackEventNotificationTest.java
  src/test/java/org/graylog/integrations/notifications/types/SlackMessageTest.java
  src/web/event-notifications/event-notification-types/SlackNotificationForm.jsx
  src/web/event-notifications/event-notification-types/SlackNotificationSummary.jsx
  src/web/index.jsx
Labels: ready-for-review, slack-plugin

#614 Disable SlackClientTest
  src/test/java/org/graylog/integrations/notifications/types/SlackClientTest.java
Labels: ready-for-review

#618 Using mock okhttpclient
  src/test/java/org/graylog/integrations/notifications/types/SlackClientTest.java
Labels: ready-for-review, slack-plugin

#606 Bring PagerDutyNotification into official integrations repo
  src/main/java/org/graylog/integrations/IntegrationsModule.java
  src/main/java/org/graylog/integrations/pagerduty/PagerDutyNotification.java
  src/main/java/org/graylog/integrations/pagerduty/PagerDutyNotificationConfig.java
  src/main/java/org/graylog/integrations/pagerduty/PagerDutyNotificationConfigEntity.java
  src/main/java/org/graylog/integrations/pagerduty/client/MessageFactory.java
  src/main/java/org/graylog/integrations/pagerduty/client/PagerDutyClient.java
  src/main/java/org/graylog/integrations/pagerduty/dto/Link.java
  src/main/java/org/graylog/integrations/pagerduty/dto/PagerDutyMessage.java
  src/main/java/org/graylog/integrations/pagerduty/dto/PagerDutyResponse.java
  src/test/java/org/graylog/integrations/pagerduty/PagerDutyNotificationTest.java
  src/test/java/org/graylog/integrations/pagerduty/client/PagerDutyClientTest.java
  src/web/index.jsx
  src/web/pager-duty/PagerDutyNotificationForm.jsx
  src/web/pager-duty/PagerDutyNotificationSummary.jsx
Labels: feature, pagerduty, ready-for-review
