Repository Graylog2/graylog-plugin-integrations, pull requests merged in 2020-02, with the labels that each got.

#387 Add documentation link
  src/web/aws/cloudwatch/kinesis/ExistingStreams.jsx
  src/web/aws/common/Routes.js
Labels: aws, ready-for-review

#389 Correctly return an unresolved authentication provider
  src/main/java/org/graylog/integrations/aws/AWSAuthFactory.java
  src/main/java/org/graylog/integrations/aws/AWSClientBuilderUtil.java
  src/main/java/org/graylog/integrations/aws/transports/KinesisConsumer.java
  src/test/java/org/graylog/integrations/aws/AWSAuthFactoryTest.java
Labels: aws, ready-for-review

#385 Bump fsevents to 1.2.11
  yarn.lock
Labels: ready-for-review

#391 Backport: Correctly return an unresolved authentication provider (#389)
  src/main/java/org/graylog/integrations/aws/AWSAuthFactory.java
  src/main/java/org/graylog/integrations/aws/AWSClientBuilderUtil.java
  src/main/java/org/graylog/integrations/aws/transports/KinesisConsumer.java
  src/test/java/org/graylog/integrations/aws/AWSAuthFactoryTest.java
Labels: ready-for-review

#401 Add documentation link for ipfixudpinput
  src/main/java/org/graylog/integrations/ipfix/inputs/IpfixUdpInput.java
Labels: documentation, ipfix, ready-for-review

#403 fix the link to ipfix docs.
  src/main/java/org/graylog/integrations/ipfix/inputs/IpfixUdpInput.java
Labels: bug

#409 Remove extra comments
  src/main/java/org/graylog/integrations/aws/AWSPolicyStatement.java
  src/main/java/org/graylog/integrations/aws/resources/KinesisSetupResource.java
  src/main/java/org/graylog/integrations/aws/resources/responses/KinesisHealthCheckResponse.java
  src/main/java/org/graylog/integrations/aws/resources/responses/KinesisNewStreamResponse.java
  src/main/java/org/graylog/integrations/aws/service/AWSService.java
  src/main/java/org/graylog/integrations/aws/service/CloudWatchService.java
  src/main/java/org/graylog/integrations/aws/service/KinesisService.java
  src/main/java/org/graylog/integrations/aws/transports/KinesisConsumer.java
  src/main/java/org/graylog/integrations/aws/transports/KinesisShardProcessorFactory.java
  src/main/java/org/graylog/integrations/aws/transports/KinesisTransport.java
Labels: aws, backend, improvement, ready-for-review

#357 Updating ThemeProvider
  src/web/aws/authentication/AWSAuthenticationTypes.jsx
  yarn.lock
Labels: ready-for-review

#418 Updating yarn lockfile due to dependency updates.
  yarn.lock
Labels: ready-for-review
