Repository Graylog2/graylog-plugin-integrations, pull requests merged in 2020-01, with the labels that each got.

#362 Updating yarn lockfile after changes.
  yarn.lock
Labels: ready-for-review

#361 Backport Kinesis Enhancements
  pom.xml
  src/main/java/org/graylog/integrations/aws/AWSAuthProvider.java
  src/main/java/org/graylog/integrations/aws/AWSClientBuilderUtil.java
  src/main/java/org/graylog/integrations/aws/AWSLogMessage.java
  src/main/java/org/graylog/integrations/aws/inputs/AWSInput.java
  src/main/java/org/graylog/integrations/aws/resources/AWSResource.java
  src/main/java/org/graylog/integrations/aws/resources/requests/AWSInputCreateRequest.java
  src/main/java/org/graylog/integrations/aws/resources/requests/AWSRequest.java
  src/main/java/org/graylog/integrations/aws/resources/requests/AWSRequestImpl.java
  src/main/java/org/graylog/integrations/aws/resources/requests/CreateLogSubscriptionRequest.java
  src/main/java/org/graylog/integrations/aws/resources/requests/CreateRolePermissionRequest.java
  src/main/java/org/graylog/integrations/aws/resources/requests/KinesisFullSetupRequest.java
  src/main/java/org/graylog/integrations/aws/resources/requests/KinesisHealthCheckRequest.java
  src/main/java/org/graylog/integrations/aws/resources/requests/KinesisNewStreamRequest.java
  src/main/java/org/graylog/integrations/aws/service/AWSService.java
  src/main/java/org/graylog/integrations/aws/service/CloudWatchService.java
  src/main/java/org/graylog/integrations/aws/service/KinesisService.java
  src/main/java/org/graylog/integrations/aws/transports/AWSPluginConfiguration.java
  src/main/java/org/graylog/integrations/aws/transports/KinesisConsumer.java
  src/main/java/org/graylog/integrations/aws/transports/KinesisShardProcessorFactory.java
  src/main/java/org/graylog/integrations/aws/transports/KinesisTransport.java
  src/test/java/org/graylog/integrations/aws/cloudwatch/CloudWatchServiceTest.java
  src/test/java/org/graylog/integrations/aws/resources/KinesisSetupResourceTest.java
  src/test/java/org/graylog/integrations/aws/service/AWSServiceTest.java
  src/test/java/org/graylog/integrations/aws/service/KinesisServiceTest.java
  src/test/java/org/graylog/integrations/aws/transports/KinesisTransportTest.java
  src/web/aws-cloudwatch/CloudWatchApp.jsx
  src/web/aws-cloudwatch/FormAdvancedOptions.jsx
  src/web/aws-cloudwatch/KinesisSetup.jsx
  src/web/aws-cloudwatch/KinesisStreams.jsx
  src/web/aws-cloudwatch/StepAuthorize.jsx
  src/web/aws-cloudwatch/StepKinesis.jsx
  src/web/aws-cloudwatch/StepReview.jsx
  src/web/aws-cloudwatch/auto-setup-steps/KinesisSetupSteps.jsx
  src/web/aws-cloudwatch/auto-setup-steps/SetupModal.jsx
  src/web/aws-cloudwatch/auto-setup-steps/SkipHealthCheck.jsx
  src/web/aws-cloudwatch/auto-setup-steps/sharedStyles.js
  src/web/aws-cloudwatch/context/AdvancedOptions.jsx
  src/web/aws-cloudwatch/context/FormData.jsx
  src/web/aws/authentication/ARN.jsx
  src/web/aws/authentication/AWSAuthenticationTypes.jsx
  src/web/aws/authentication/AWSCustomEndpoints.jsx
  src/web/aws/authentication/Automatic.jsx
  src/web/aws/authentication/KeySecret.jsx
  src/web/common/AdditionalFields.jsx
  src/web/common/MaskedInput.jsx
  src/web/common/ValidatedInput.jsx
  src/web/common/constants.js
  src/web/common/hooks/useFetch.js
  src/web/utils/formValidation.js
  yarn.lock
Labels: ready-for-review

#378 Support lists in IPFIX data sets
  src/main/java/org/graylog/integrations/ipfix/IpfixParser.java
  src/main/java/org/graylog/integrations/ipfix/codecs/IpfixAggregator.java
  src/main/java/org/graylog/integrations/ipfix/codecs/IpfixCodec.java
  src/test/java/org/graylog/integrations/ipfix/IpfixParserTest.java
  src/test/java/org/graylog/integrations/ipfix/codecs/IpfixAggregatorTest.java
  src/test/resources/ixflow.pcap
  src/test/resources/ixia-ied.json
  src/test/resources/ixia-multilist.ipfix
  src/test/resources/log4j2-test.xml
Labels: backend, ipfix, ready-for-review

#376 Bump set-value to 2.0.1
  yarn.lock
Labels: ready-for-review, security

#382 Bump serialize-javascript to 2.1.2
  yarn.lock
Labels: ready-for-review, security
