Repository Graylog2/graylog-plugin-integrations, pull requests merged in 2021-11, with the labels that each got.

#939 Renames OS GreyNoise adapter and adds User-Agent header
  src/main/java/org/graylog/integrations/IntegrationsModule.java
  src/main/java/org/graylog/integrations/dataadapters/GreyNoiseQuickIPDataAdapter.java
  src/test/java/org/graylog/integrations/dataadapters/GreyNoiseDataAdapterTest.java
  src/web/dataadapters/GreyNoiseAdapterDocumentation.jsx
  src/web/index.jsx
Labels: threat intel

#932 Upgrade aws-java-sdk to fix IRSA on EKS
  pom.xml
  src/test/java/org/graylog/integrations/aws/service/AWSServiceTest.java
Labels: ready-for-review

#943 Renames OS GreyNoise adapter and adds User-Agent header (#939)
  src/main/java/org/graylog/integrations/IntegrationsModule.java
  src/main/java/org/graylog/integrations/dataadapters/GreyNoiseQuickIPDataAdapter.java
  src/test/java/org/graylog/integrations/dataadapters/GreyNoiseDataAdapterTest.java
  src/web/dataadapters/GreyNoiseAdapterDocumentation.jsx
  src/web/index.jsx
Labels: backport, threat intel

#940 Community greynoise iplookup adapter
  src/main/java/org/graylog/integrations/IntegrationsModule.java
  src/main/java/org/graylog/integrations/dataadapters/GreyNoiseCommunityIpLookupAdapter.java
  src/test/java/org/graylog/integrations/TestWithResources.java
  src/test/java/org/graylog/integrations/dataadapters/GreyNoiseCommunityIpLookupAdapterTest.java
  src/test/resources/org/graylog/integrations/dataadapters/GreyNoiseCommunityIpLookupAdapter_test-parse-404.json
  src/test/resources/org/graylog/integrations/dataadapters/GreyNoiseCommunityIpLookupAdapter_test-parse-LimitReached.json
  src/test/resources/org/graylog/integrations/dataadapters/GreyNoiseCommunityIpLookupAdapter_test-parse-success.json
  src/web/dataadapters/GreyNoiseCommunityIpLookupAdapterDocumentation.jsx
  src/web/index.jsx
Labels: ready-for-review
