Repository Graylog2/graylog-plugin-integrations, pull requests merged in 2022-01, with the labels that each got.

#951 Adds riot field to GreyNoise quickip lookup adapter
  src/main/java/org/graylog/integrations/dataadapters/GreyNoiseQuickIPDataAdapter.java
Labels: threat intel

#958 Adds riot field to GreyNoise quickip lookup adapter (#951)
  src/main/java/org/graylog/integrations/dataadapters/GreyNoiseQuickIPDataAdapter.java
Labels: backport

#953 Updated GreyNoiseCommunityIpLookupAdapter to exclude 'message' field,…
  pom.xml
  src/main/java/org/graylog/integrations/dataadapters/GreyNoiseCommunityIpLookupAdapter.java
  src/test/java/org/graylog/integrations/dataadapters/GreyNoiseCommunityIpLookupAdapterTest.java
Labels: ready-for-review

#960 Merge pull request #953 from Graylog2/update-greynoise-comm-adapter
  pom.xml
  src/main/java/org/graylog/integrations/dataadapters/GreyNoiseCommunityIpLookupAdapter.java
  src/test/java/org/graylog/integrations/dataadapters/GreyNoiseCommunityIpLookupAdapterTest.java
Labels: ready-for-review, backport
